#!/usr/bin/env python

import sys
import os
try:
    import siptracklib
    import siptracklib.commands
except ImportError as e:
    print("ERROR: unable to import siptracklib", file=sys.stderr)
    print("verify that siptracklib is in your PYTHONPATH", file=sys.stderr)
    raise

class NullStream(object):
    def write(self, text):
        pass

def main():
    if os.path.basename(sys.argv[0]).startswith('siptrack-no-console'):
        stream = NullStream()
        sys.stdout = stream
        sys.stderr = stream
    sys.exit(siptracklib.commands.main(sys.argv))

if __name__ == '__main__':
    main()
